### ISSUE TITLE
Get error with zsh-nix-shell activated

### ISSUE THREAD

**Issue by nikivdev** [chisui/zsh-nix-shell#1]
I installed this plugin with [Antibody](https://github.com/getantibody/antibody) and tried to test nix-shell but I got an error:

```bash
❯ nix-shell -p hello
whereis: illegal option -- b
usage: whereis program [...]
nix-shell:2: bad pattern: ARGS=(-p
```

However if I stop using this plugin, it works with no errors:
```bash
❯ nix-shell -p hello

[nix-shell:~]$
```

Not sure why this happens.

**Comment by chisui** [comment]
I have never heard of antibody so it's not supported currently.

What shell and version are you using?

Does it work if you install it directly?

**Comment by nikivdev** [comment]
> What shell and version are you using?

```bash
❯ zsh --version
zsh 5.5.1 (x86_64-apple-darwin16.6.0)
```



> Does it work if you install it directly?

I tried to put contents of [this file](https://github.com/chisui/zsh-nix-shell/blob/master/nix-shell.plugin.zsh) to the end of my zshrc.

Same error.

**Comment by chisui** [comment]
I could not reproduce this bug with `zsh 5.5.1` on NixOs. I don't have access to a Mac but going by [this](https://github.com/phpbrew/phpbrew/issues/503) and [this](https://code.djangoproject.com/ticket/3641) issue it seems that `whereis` works diffently on Mac.

Does #2 fix your issue?

**Comment by nikivdev** [comment]
It does not. I get this error now:

```bash
❯ nix-shell -p hello
nix-shell:2: bad pattern: ARGS=(-p

~
```

Here is [my zshrc with your plugin](https://github.com/nikitavoloboev/dotfiles/blob/master/zsh/zshrc.zsh#L12).

**Comment by chisui** [comment]
I can't reproduce that issue and I double checked the zsh documentation. There was an error in `zsh-5.0.8` though that looks like this.

I changed some stuff around in #2. Is it working now?

**Comment by nikivdev** [comment]
It's solved. Thanks @chisui
