### ISSUE TITLE
Breaks pypi2nix

### ISSUE THREAD

**Issue by lovesegfault** [chisui/zsh-nix-shell#15]
## Issue description

I'm adding this issue a few days after it happened, so it's no longer fresh on my head but basically there is some weird interaction between this and `pypi2nix` where it (`pypi2nix`) fails to launch the shell with the generated Python environment

### Steps to reproduce
1. Pick a PyPI project (e.g. https://github.com/beetbox/beets)
2. `pypi2nix` (You may need `-r requirements.txt` depending on the project)

## Technical details

Please run the following commands and paste the results:
1. `command nix-shell -p nix-info --run "nix-info -m"`
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.5, NixOS, 20.03pre206137.f5bb6c02071 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-20.03pre206137.f5bb6c02071"`
 - channels(bemeurer): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
2. `zsh --version`
```
zsh 5.7.1 (x86_64-pc-linux-gnu)
```

**Comment by chisui** [comment]
Sorry, but I'm not a python guy. Can you provide more detailed steps to reproduce your issue? The beets project doesn't contain a `requriements.txt` and [in the travis config they seem to manually install their dependencies](https://github.com/beetbox/beets/blob/master/.travis.yml#L58).
