### ISSUE TITLE
Any way to indicate that you are in a nix-shell?

### ISSUE THREAD

**Issue by drewboardman** [chisui/zsh-nix-shell#18]
Plugin is great. However it's opaque whether or not you're in a nix shell. Is there a way to configure `zshrc` to indicate when you are in fact in a nix shell?

**Comment by chisui** [comment]
The [Environment info section of the Readme](https://github.com/chisui/zsh-nix-shell#environment-info) describes how to retrieve infos about the current environment.

Tl;dr: `IN_NIX_SHELL` is set to `1` use that to customize your prompt.
