### ISSUE TITLE
Support for `nix develop`

### ISSUE THREAD

**Issue by johnrichardrinehart** [chisui/zsh-nix-shell#27]
First, thanks for writing this!

## Issue description

I use flakes for development, mostly. `nix develop` is the [new version of `nix-shell`](https://nixos.wiki/wiki/Flakes#Using_nix_flakes_with_NixOS). Can you support using `zsh` when `nix develop` is ran?

### Steps to reproduce

Run `nix develop` with a version of `nix` that supports flakes.

**Comment by chisui** [comment]
Similarly to #17 the new nix cli works completely differently to the old one. Supporting it would be the same as writing a new plugin. Additionally the way it handles interactive shells isn't finalized. For now I will only support `nix-shell`.

**Comment by johnrichardrinehart** [comment]
Fair enough. Let's say that some ambitious, intrepid `nix`er wanted to spin up a version of this that would work with `nix develop`. What projects could they consult and where in the manual/Wiki might they find information that would help them get started?

**Comment by chisui** [comment]
To be honest, I just look at the c++ code and pester the people on the #nixos IRC. And a bunch of trial and error.

**Comment by johnrichardrinehart** [comment]
Okay, it sounds like you and I have similar levels of knowledge. Deal. I'll try to find some time to work on this.

Thanks for `zsh-nix-shell`, @chisui . It's really helpful.
