### ISSUE TITLE
Shadowing shell.nix binary

### ISSUE THREAD

**Issue by soulomoon** [chisui/zsh-nix-shell#32]
## Issue description
I have some build tools binary to add in in my shell.nix.
It shadows build tools in shell.nix script if zsh's initExtra export the path contains the same binary.

**Comment by chisui** [comment]
Yes, this is a current limitation that I don't know how to fix without great effort. A workaround is to only add the binaries to the path if `IN_NIX_SHELL` is not set.

Also see: #19
