### ISSUE TITLE
Support `nom-shell`

### ISSUE THREAD

**Issue by hacker1024** [chisui/zsh-nix-shell#38]
[nix-output-monitor](https://github.com/maralorn/nix-output-monitor) adds a `nom-shell` command that is a drop-in replacement for `nix-shell`. It'd be great if zsh-nix-shell supported this as well.

**Comment by chisui** [comment]
It seems that the project is aimed more at builds. This plugin is meant for interactive environments. Furthermore the project describes itself as experimental.

I wont add support for nom PRs are welcome though
