### ISSUE TITLE
How to calculate sha256 hash

### ISSUE THREAD

**Issue by voidzero** [chisui/zsh-nix-shell#39]
This question is fully beside the package itself, but how did you calculate the hash? Because the hash is longer (doesn't look as an sri) and it works even though I specified v0.7.0 :) So my curiosity is piqued.

**Comment by chisui** [comment]
I updated the version and hash in the readme.

---

I calculate the hash using `nix-prefetch-url` like this:

```sh
nix-prefetch-url --unpack https://github.com/chisui/zsh-nix-shell/archive/refs/tags/v0.7.0.tar.gz
```
