### ISSUE TITLE
Update bash reference

### ISSUE THREAD

**Issue by shakefu** [chisui/zsh-nix-shell#40]
https://github.com/chisui/zsh-nix-shell/blob/406ce293f5302fdebca56f8c59ec615743260604/scripts/buildShellShim#L22

The reference here and below just invokes "bash" - on OSX this can be a problem since /bin/bash has precedence and is 3.x

Instead you can use `/usr/bin/env bash` to pick up a Homebrew install or custom bash binary in /usr/bin/local which can then match the correct version.

**Comment by chisui** [comment]
Thanks, is included in [release v0.8.0](https://github.com/chisui/zsh-nix-shell/releases/tag/v0.8.0)
